### ISSUE TITLE
How to change fonts in the Primer theme?

### ISSUE THREAD

**Issue by nelvintan** [pages-themes/primer#50]
How do you change the fonts in the primer theme? I've tried to follow the [instructions](https://github.com/pages-themes/primer#usage), i.e., to create an `assets/css/style.scss` file and add:
```
---
---

@import "{{ site.theme }}";
body {
  font-family: "Times New Roman", Times, serif;
}
```
However, I don't see any changes in the font used on my github page. What am I doing wrong? Or is there a simpler way to do this? Thanks,

**Comment by seshrs** [comment]
You're changing the styles in the right place, but your styles are overridden by those set by the theme itself because of [CSS Specificity rules](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).

You can debug CSS rules in most browser developer tools. For instance, I set up an example page and applied your stylesheet changes. I opened [Chrome's developer tools](https://developer.chrome.com/docs/devtools/overview/) and inspected the heading:

<img width="1440" alt="Screen Shot 2021-04-21 at 10 43 02 PM" src="https://user-images.githubusercontent.com/12139762/115648498-865e1f00-a2f3-11eb-8bcd-26620960b6ba.png">


We'll need to match or exceed the specificity levels from the theme. Hence, the following CSS would work:
```css
.markdown-body {
  font-family: 'Times New Roman', Times, serif;
}
```

Alternatively, you could use [`!important`](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#the_!important_exception) to override specificity rules, but it's a bit of a sledgehammer — it's usually a good idea not to overuse it.

```css
body {
  font-family: 'Times New Roman', Times, serif !important;
}
```

**Comment by nelvintan** [comment]
Works now, thanks!

**Comment by nelvintan** [comment]
Works now, thanks!
